---

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            lfs: true

      - name: Rust toolchain install
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable

      - name: Build
        env:
          MDBOOK_VERSION: 0.4.25
          MDBOOK_ADMONISH_VERSION: 1.8.0
          MDBOOK_LINKCHECK_VERSION: 0.7.7
        run: |
          cargo install mdbook --no-default-features  --features search --vers ${MDBOOK_VERSION}
          cargo install mdbook-admonish --vers ${MDBOOK_ADMONISH_VERSION}
          cargo install mdbook-linkcheck --vers ${MDBOOK_LINKCHECK_VERSION}
          mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          cname: tech-docs.crabikboards.com